version: '3.8'

services:
  raines-catalog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    ports:
      - "8090:80"
    restart: unless-stopped
    container_name: raines-catalog
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  raines-server:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    ports:
      - "8091:5000"
    restart: unless-stopped
    container_name: raines-server
