import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#ffffff',
        padding: 30,
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#112233',
        paddingBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#112233',
    },
    subtitle: {
        fontSize: 12,
        color: '#666666',
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
    },
    table: {
        display: "table",
        width: "auto",
        borderStyle: "solid",
        borderWidth: 1,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        marginTop: 20,
    },
    tableRow: {
        margin: "auto",
        flexDirection: "row"
    },
    tableCol: {
        width: "25%",
        borderStyle: "solid",
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
    },
    tableCell: {
        margin: 5,
        fontSize: 10
    },
    tableHeader: {
        backgroundColor: '#f0f0f0',
        fontWeight: 'bold',
    },
    totalSection: {
        marginTop: 20,
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    totalText: {
        fontSize: 14,
        fontWeight: 'bold',
    }
});

export const KitPDF = ({ items, total }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <View>
                    <Text style={styles.title}>AISAC Reporting</Text>
                    <Text style={styles.subtitle}>Med-Kit Configuration Status</Text>
                </View>
                <Text style={styles.subtitle}>{new Date().toLocaleDateString()}</Text>
            </View>

            <View style={styles.table}>
                <View style={styles.tableRow}>
                    <View style={[styles.tableCol, styles.tableHeader]}><Text style={styles.tableCell}>Item</Text></View>
                    <View style={[styles.tableCol, styles.tableHeader]}><Text style={styles.tableCell}>Category</Text></View>
                    <View style={[styles.tableCol, styles.tableHeader]}><Text style={styles.tableCell}>ID</Text></View>
                    <View style={[styles.tableCol, styles.tableHeader]}><Text style={styles.tableCell}>Price</Text></View>
                </View>

                {items.map((item, index) => (
                    <View style={styles.tableRow} key={index}>
                        <View style={styles.tableCol}><Text style={styles.tableCell}>{item.name}</Text></View>
                        <View style={styles.tableCol}><Text style={styles.tableCell}>{item.category}</Text></View>
                        <View style={styles.tableCol}><Text style={styles.tableCell}>{item.item_id}</Text></View>
                        <View style={styles.tableCol}><Text style={styles.tableCell}>€{item.price.toFixed(2)}</Text></View>
                    </View>
                ))}
            </View>

            <View style={styles.totalSection}>
                <Text style={styles.totalText}>Total Value: €{total.toFixed(2)}</Text>
            </View>

            <View style={{ position: 'absolute', bottom: 30, left: 30, right: 30 }}>
                <Text style={{ fontSize: 8, color: 'grey', textAlign: 'center' }}>Generated by AISAC Ghost-Inventory System</Text>
            </View>
        </Page>
    </Document>
);
